// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/filmes/{filmeId}/reservas": {
            "get": {
                "description": "Retorna todas as reservas confirmadas para o filme informado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservas"
                ],
                "summary": "Lista as reservas de um filme",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do filme",
                        "name": "filmeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_marlonseben_cinema-booking_internal_reservas.Reserva"
                            }
                        }
                    }
                }
            }
        },
        "/reservas": {
            "post": {
                "description": "Confirma a reserva de um assento para um filme, de forma serializada por assento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservas"
                ],
                "summary": "Reserva um assento",
                "parameters": [
                    {
                        "description": "Dados da reserva",
                        "name": "reserva",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.reservarRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_marlonseben_cinema-booking_internal_reservas.Reserva"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.erroResponse"
                        }
                    },
                    "409": {
                        "description": "Assento já ocupado",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.erroResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.erroResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_marlonseben_cinema-booking_internal_reservas.Reserva": {
            "type": "object",
            "properties": {
                "assentoID": {
                    "type": "string"
                },
                "filmeID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "usuarioID": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.erroResponse": {
            "type": "object",
            "properties": {
                "erro": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.reservarRequest": {
            "type": "object",
            "properties": {
                "assento_id": {
                    "type": "string",
                    "example": "A1"
                },
                "filme_id": {
                    "type": "string",
                    "example": "matrix"
                },
                "usuario_id": {
                    "type": "string",
                    "example": "marlon"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cinema Booking API",
	Description:      "API para reserva de assentos de cinema, com locking pessimista distribuído via RabbitMQ.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
